name: Say hello

on:
  push:
    branches:
      - master

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: |
          echo "Hola mundo"
      - name: Fecha
        run: date
      - run: ls -l


